#!/bin/bash
### BEGIN INIT INFO
# Provides:             socat
# Required-Start:       $remote_fs $syslog
# Required-Stop:        $remote_fs $syslog
# Default-Start:        2 3 4 5
# Default-Stop:
# Short-Description:    socat service
### END INIT INFO

USER=nobody
GROUP=nogroup
TARGET=$3
INPORT=$2
DSTPORT=$4
PIDFILE=/var/run/socat-$INPORT.pid
LOGFILE=/var/log/socat-$INPORT.log
SOCAT=/usr/bin/socat

start() {
  $SOCAT TCP4-LISTEN:$INPORT,fork,reuseaddr TCP4:$TARGET:$DSTPORT </dev/null > $LOGFILE &
  echo $! >$PIDFILE
}

stop() {
  /bin/kill $(/bin/cat $PIDFILE)
}

restart() {
  stop
  start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  *)
    echo $"Use this options $0 {start|stop|restart}"
    exit 1
esac
exit $?    
